services:
  db:
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_DB: consents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40

  consents-api:
    build: .
    restart: always
    ports:
      - "${CONSENTS_API_PORT}:8000"
    environment:
      DATABASE_URI: postgresql://postgres:example@db:5432/consents
    volumes:
      - ./project/:/app:cached
    depends_on:
      db:
        condition: service_healthy

  migrator:
    build: .
    restart: "no"
    command: bash -c " python manage.py makemigrations users assets consents && python manage.py migrate && python manage.py admin_from_env "
    environment:
      DATABASE_URI: postgresql://postgres:example@db:5432/consents
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_ADDRESS: ${ADMIN_ADDRESS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./project/:/app:rw

  tester:
    build: .
    restart: "no"
    command: bash -c "python manage.py test -v 2"
    environment:
      DATABASE_URI: postgresql://postgres:example@db:5432/consents
    volumes:
      - ./project/:/app:ro
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

volumes:
  pgdata:
