---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: consents-api
  name: consents-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consents-api-app
  template:
    metadata:
      labels:
        app: consents-api-app
    spec:
      containers:
        - name: app
          image: consents_api:latest
          readinessProbe:
            httpGet:
              path: /api/health
              port: api-port
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: CONSENTS_API_HOST
              value: "0.0.0.0"
            - name: CONSENTS_API_WORKERS_COUNT
              value: "10"
            - name: CONSENTS_API_DB_HOST
              value: "consents-api-db-service"
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 8000
              name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: consents-api
  name: consents-api-app-service
spec:
  selector:
    app: consents-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
      name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consents-api-app
  namespace: consents-api
  labels:
    name: consents-api-app
spec:
  rules:
    - host: consents-api.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: consents-api-app-service
                port:
                  name: api-port

---
